package ir.demisco.cfs.service.api;

import ir.demisco.cfs.model.dto.request.ControlFinancialAccountNatureTypeByAccountRequest;
import ir.demisco.cfs.model.dto.request.ControlFinancialAccountNatureTypeInputRequest;
import ir.demisco.cfs.model.dto.response.ControlFinancialAccountNatureTypeByAccountResponse;
import ir.demisco.cfs.model.dto.response.ControlFinancialAccountNatureTypeOutputResponse;

import java.util.List;

public interface ControlFinancialAccountNatureTypeService {
    List<ControlFinancialAccountNatureTypeByAccountResponse> getFinancialNatureControlByAccount(ControlFinancialAccountNatureTypeByAccountRequest controlFinancialAccountNatureTypeByAccountRequest);

    List<ControlFinancialAccountNatureTypeOutputResponse> getControlFinancialAccountNatureType(ControlFinancialAccountNatureTypeInputRequest controlFinancialAccountNatureTypeInputRequest);


}
